<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_REGISTER</name>
   <tag></tag>
   <elementGuidId>8added63-5f29-406b-8604-b2ddc7a56ede</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.btn-style2.btn-join.mt-2.fs-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/section/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e83c41a-e5c8-4c55-9a51-a7c54a5d42ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-style2 btn-join mt-2 fs-3</value>
      <webElementGuid>d896bef4-9ea3-424e-9eb9-9c84b8bc4229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/registration</value>
      <webElementGuid>7dbbdb64-192f-4bf9-b168-f19429481c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-discover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1b95fcf5-f9a9-4db3-aa62-3228aaea11a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REGISTER </value>
      <webElementGuid>28bbfb20-ac95-4bfe-81a9-5b18d6f39450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;lp-wrapper&quot;]/section[@class=&quot;lp-banner-wrapper mms-landing-banner text-center&quot;]/div[@class=&quot;lp-banner-contain container d-flex align-items-center flex-column&quot;]/a[@class=&quot;btn btn-primary btn-style2 btn-join mt-2 fs-3&quot;]</value>
      <webElementGuid>3951e7b3-4ec0-4906-a013-55bbe2a37b66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/a</value>
      <webElementGuid>ad06aaca-3ed0-4b42-8064-0795ce00a45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'REGISTER')]</value>
      <webElementGuid>f9d55b9c-3c45-43cd-9a94-6227c1a0d08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Walpole Youth Football &amp; Cheer'])[1]/following::a[1]</value>
      <webElementGuid>ab7c3115-762b-4aff-8c98-a13e9253e577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[1]</value>
      <webElementGuid>432ad972-94f7-489a-916c-3b22852b6fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prerequisites to Your Membership Registration'])[1]/preceding::a[1]</value>
      <webElementGuid>5e80a7ec-99c5-4e0b-ba87-4d0113f822d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Clearance'])[1]/preceding::a[1]</value>
      <webElementGuid>d859f063-dd81-43fb-b917-2ae258d84361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REGISTER']/parent::*</value>
      <webElementGuid>e74c8b8c-eb31-4581-95a1-595a9e84718d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/registration')]</value>
      <webElementGuid>364fc163-54c5-4f76-99d5-0323aed19a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>a1a46906-a91b-4bb2-a57b-a916de050de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/registration' and (text() = 'REGISTER ' or . = 'REGISTER ')]</value>
      <webElementGuid>126ac7c0-fcc9-468c-9c32-93923619fc93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
