<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_REGISTER</name>
   <tag></tag>
   <elementGuidId>c61cf20c-2d01-4d1b-82ca-195ce53d9499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/section/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.btn-style2.btn-join.mt-2.fs-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;REGISTER&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>176eb87c-3aed-4c45-acc7-456d2cbf88f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-style2 btn-join mt-2 fs-3</value>
      <webElementGuid>7042a67d-e1f6-4931-a2c5-6f25977b357d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/registration</value>
      <webElementGuid>4dfc14ca-cb4f-4dfa-a8f6-3a5a6aa9f8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-discover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1b6a988b-7616-44bd-ba37-1108ab1dcf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REGISTER </value>
      <webElementGuid>5d972db4-a716-4947-bdb5-ee8b2ce27055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;lp-wrapper&quot;]/section[@class=&quot;lp-banner-wrapper mms-landing-banner text-center&quot;]/div[@class=&quot;lp-banner-contain container d-flex align-items-center flex-column&quot;]/a[@class=&quot;btn btn-primary btn-style2 btn-join mt-2 fs-3&quot;]</value>
      <webElementGuid>28758008-9185-4252-9c7c-33edbcd4b205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/a</value>
      <webElementGuid>84e9c238-55a4-4b9f-9a4d-6f737b0df28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'REGISTER')]</value>
      <webElementGuid>a6cef975-6891-483d-ab5e-4fb333e1c1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Walpole Youth Football &amp; Cheer'])[1]/following::a[1]</value>
      <webElementGuid>ec80c83b-76b6-4a29-aae7-6aeffaa3973e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[1]</value>
      <webElementGuid>bdd48be9-8532-4960-b95c-370dcec9e4cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prerequisites to Your Membership Registration'])[1]/preceding::a[1]</value>
      <webElementGuid>fb2acfbb-7ef5-4ee5-9bb0-d955769685b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Clearance'])[1]/preceding::a[1]</value>
      <webElementGuid>53940694-3310-4c4b-81a7-798ed9e3a73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REGISTER']/parent::*</value>
      <webElementGuid>5299aa6f-b0a9-4169-a463-08be42a77f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/registration')]</value>
      <webElementGuid>386422fa-2287-4bde-8613-e15cebc71648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>3ecfc603-ce76-43b0-b4c9-66056f6aab98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/registration' and (text() = 'REGISTER ' or . = 'REGISTER ')]</value>
      <webElementGuid>65928d12-82e7-45c3-8ec2-f6128b429a70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
