<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CoachVolunteer_membership_id</name>
   <tag></tag>
   <elementGuidId>bdf5f0ee-01f1-459c-b3ee-24e70e37bcc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div[2]/div/div/div/div/div[2]/div[2]/div/form/div/div[3]/div/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#membership_38</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Coach/Volunteer - Tackle&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0994f34d-45f8-487c-af7a-ddada612a270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>membership_id</value>
      <webElementGuid>d3076d0f-7595-4db6-acfd-f822845e5e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5b4f23c4-10a6-4308-beb8-1ace92ca3ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Coach/Volunteer - Tackle</value>
      <webElementGuid>cebe70bb-6b83-4889-8f60-292be9b89dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>membership_38</value>
      <webElementGuid>3b293a3c-270a-4daf-b872-6de92413959d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>c8ff6588-c77f-478e-9146-4c29aeef89e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;membership_38&quot;)</value>
      <webElementGuid>c19e2e72-b269-455c-938b-35a82e32441a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='membership_38']</value>
      <webElementGuid>9691a6c6-90ed-4d0a-85d7-db60c71f79f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/div/div/div/div/div[2]/div[2]/div/form/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>7695999c-0a16-4ed1-a5f6-d026cbb6ef1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>2e8a317a-7909-4c87-a74c-9bcf9c6e0aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'membership_id' and @type = 'radio' and @id = 'membership_38']</value>
      <webElementGuid>4b56505f-a10e-4950-8f62-d13917c838c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
