<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tackle Football_membership_1</name>
   <tag></tag>
   <elementGuidId>6ddf2f4c-aa40-460d-8cf9-f2ae503c1ae4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#membership_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='membership_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#membership_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1937919-67d4-461f-86ff-6483cc863d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>dc2d884b-1bf2-4839-ba8b-c8cd323a9d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>membership_1</value>
      <webElementGuid>0f7f5df9-9439-4353-aa15-6897bf5666d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b737797f-c151-4f41-a76e-09747e44a2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8f84def5-5fa3-4710-a911-5decb91cdaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;membership_1&quot;)</value>
      <webElementGuid>39e0fddd-7ed3-4b18-96a0-56b01ad0a97d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='membership_1']</value>
      <webElementGuid>2812d092-56ff-4e7c-bc03-c28d6cbf5d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div/form/div/div[3]/div/input</value>
      <webElementGuid>2136c858-50b5-4c31-b36d-5ac9c35502e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>c71a2b54-d854-4816-9302-9af017e0ce06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'membership_1']</value>
      <webElementGuid>4aa7227b-e3c0-4bce-b132-ea7f46ac0adc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
